---
title: "week3"
output: html_document
date: "2023-08-04"
runtime: shiny
---

```{r}
# Load required libraries

library(shiny)
library(ggplot2)

# load dataset
df <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";")

# Define the UI
ui <- fluidPage(
    titlePanel("Histogram Visualization"),
    sidebarLayout(
        sidebarPanel(
            selectInput(inputId = "x1", label = "Choose X:", choices = names(df))
        ),
        mainPanel(
            plotOutput(outputId = "histogram")
        )
    )
)

# Define the server
server <- function(input, output) {
    generate_histogram <- function(data, x_var, title) {
        ggplot(data, aes_string(x = x_var)) +
        geom_histogram(bins = 20, color = "white") +
        labs(title = title, x = x_var, y = "Frequency")
    }
    # Render the side-by-side histograms
    output$histogram <- renderPlot({
        generate_histogram(df, input$x1, colnames(input$x1))
        })
}
# Run the Shiny app
shinyApp(ui = ui, server = server)
```

## Answer for two historgrams:

```{r}
# Load required libraries
library(shiny)
library(ggplot2)
library(gridExtra)


df <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";")

# Define the UI
ui <- fluidPage(
    titlePanel("Histogram Visualization"),
    sidebarLayout(
        sidebarPanel(
            selectInput("x_var1", "Choose x for Histogram 1:", choices = names(df)),
            selectInput("x_var2", "Choose x for Histogram 2:", choices = names(df))
        ),
        mainPanel(plotOutput("histogram"))
    )
)


# Define the server
server <- function(input, output){
    # Function to generate the histogram plots
    generate_histograms <- function(data, x_var, title){
        ggplot(data, aes_string(x = x_var)) +
        geom_histogram(bins = 20, color = "white") +
        labs(x = x_var, y = "Frequency")
    }

    # Render the side-by-side histograms
    output$histogram <- renderPlot({
        hist_residual_sugar <- generate_histograms(df, input$x_var1)
        hist_fixed_acidity <- generate_histograms(df, input$x_var2)
        # Arrange the histograms side by side using grid.arrange
        grid.arrange(hist_residual_sugar, hist_fixed_acidity, ncol = 2)
    })
}

# Run the Shiny app
shinyApp(ui = ui, server = server)
```

## Answer for Scatter:

```{r}
# Load required libraries
library(shiny)
library(ggplot2)

df <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv", sep=";")

# Define the UI
ui <- fluidPage(
  titlePanel("Scatterplot Visualization"),
  sidebarLayout(
    sidebarPanel(
      selectInput("x_var", "Choose x:",
                  choices = names(df)),
      selectInput("y_var", "Choose y:",
                  choices = names(df))
    ),
    mainPanel(
      plotOutput("scatter")
    )
  )
)

# Define the server
server <- function(input, output) {
  # Function to generate the scatterplot
  generate_scatterplot <- function(data, x_var, y_var) {
    ggplot(data, aes_string(x = x_var, y = y_var)) +
      geom_point() +
      labs(title = "Scatterplot", x = x_var, y = y_var)
  }

  # Render the scatterplot
  output$scatter <- renderPlot({
    scatterplot <- generate_scatterplot(df, input$x_var, input$y_var)
    print(scatterplot)
  })
}

# Run the Shiny app
shinyApp(ui = ui, server = server)
```
